/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:e26e2175-5372-4e19-bbd8-334a375c3b45",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_JUHV7OARV",
    "aws_user_pools_web_client_id": "312islnf8nnto9ejgpio61okh5",
    "oauth": {}
};


export default awsmobile;
